- platform: group
  name: Living Room Ceiling
  entities:
    - light.living_room_ceiling_a
    - light.living_room_ceiling_b
    - light.living_room_ceiling_c
- platform: group
  name: Bedroom Ceiling
  entities:
    - light.bedroom_ceiling_front
    - light.bedroom_ceiling_rear
