version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    restart: always
  ports:
    - "450:443"
    - "90:80"
  environment:
    - PUID: 998
    - PGID: 100
    - TZ=Europe/Berlin
    - EMAIL=shreyansqt@gmail.com
    - URL=grumpyorange.duckdns.org
    - VALIDATION=http
  volumes:
    - /home/pi/home-media-server/lets-encrypt/config:/config
  cap_add:
    - NET_ADMIN
  networks:
    - my-net
